### ISSUE TITLE
KeyError: 'version'

### ISSUE THREAD

**Issue by zregvart** [containerbuildsystem/cachi2#434]
I'm trying to use cachi2 with https://github.com/devfile-samples/devfile-stack-nodejs-nextjs.git and I'm getting:

```
KeyError: 'version'
Traceback (most recent call last):

  File "/usr/local/bin/cachi2", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/src/cachi2/interface/cli.py", line 42, in cmd_with_error_handling
    cmd(*args, **kwargs)

  File "/src/cachi2/interface/cli.py", line 240, in fetch_deps
    request_output = resolve_packages(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/src/cachi2/core/resolver.py", line 32, in resolve_packages
    return _merge_outputs(pkg_manager(request) for pkg_manager in pkg_managers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/src/cachi2/core/resolver.py", line 41, in _merge_outputs
    for output in outputs:

  File "/src/cachi2/core/resolver.py", line 32, in <genexpr>
    return _merge_outputs(pkg_manager(request) for pkg_manager in pkg_managers)
                          ^^^^^^^^^^^^^^^^^^^^

  File "/src/cachi2/core/package_managers/npm.py", line 664, in fetch_npm_source
    info = _resolve_npm(request.source_dir.join_within_root(package.path), npm_deps_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/src/cachi2/core/package_managers/npm.py", line 726, in _resolve_npm
    "package": original_package_lock.get_main_package(),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/src/cachi2/core/package_managers/npm.py", line 283, in get_main_package
    version = self._lockfile_data["version"]
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
```

**Comment by taylormadore** [comment]
@zregvart Apologies for not noticing this before now. I think it got lost in the end-of-year shuffle.

In this case, it looks like you are working with an npm package where `private: true` is set in package.json and the `version` key is missing.

> If you plan to publish your package, the most important things in your package.json are the name and version fields as they will be required. The name and version together form an identifier that is assumed to be completely unique. Changes to the package should come along with changes to the version. If you don't plan to publish your package, the name and version fields are optional. [1]

Since the version is reported in the SBOM by cachi2, we would need to determine first if private packages should be processed and if so, how they should be reported in the SBOM.

[1] https://docs.npmjs.com/cli/v10/configuring-npm/package-json#version

**Comment by eskultety** [comment]
Closing per https://github.com/containerbuildsystem/cachi2/issues/434#issuecomment-2018221306. If the issue persists, please re-open with new information.
