### ISSUE TITLE
Log the root cause why git remote fetch python fails

### ISSUE THREAD

**Issue by cmoulliard** [containerbuildsystem/cachi2#685]
## Issue

When this code [fails](https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/package_managers/gomod.py#L1172-L1184) then cachi2 reports such a message
```
step-prefetch-dependencies
INFO: Using mounted CA bundle: /mnt/trusted-ca/ca-bundle.crt
'/mnt/trusted-ca/ca-bundle.crt' -> '/etc/pki/ca-trust/source/anchors/ca-bundle.crt'
2024-10-15 12:49:16,848 DEBUG Testing for go mod file in /var/workdir/source/jam/go.mod
2024-10-15 12:49:16,848 DEBUG Testing for go mod file in /var/workdir/source/create-package/go.mod
2024-10-15 12:49:16,848 DEBUG Testing for go mod file in /var/workdir/source/pack/go.mod
2024-10-15 12:49:17,255 ERROR FetchError: Failed to fetch the tags on the Git repository (GitCommandError) for /var/workdir/source
```
which is missing why git failed. That will not help the users to figure out what they should do !
The root cause or stack trace should be logged. See hereafter:
```
Traceback (most recent call last):
  File "/var/workdir/source/.tekton/git-fetch.py", line 23, in fetch_git_tags
    repo.remote().fetch(force=True, tags=True)
  File "/venv/lib64/python3.9/site-packages/git/remote.py", line 1069, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "/venv/lib64/python3.9/site-packages/git/remote.py", line 895, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/venv/lib64/python3.9/site-packages/git/cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v --force --tags -- origin
  stderr: 'fatal: remote error: upload-pack: not our ref f06ea2185060f86690509c03faa793875bf0e221'
Current commit: 262cc4839eae9a07cd8ed0839ab33a15aad5f056
Failed to fetch the tags on the Git repository (GitCommandError) for /var/workdir/source
```

**Comment by eskultety** [comment]
Thank you for reporting this. This will likely be a problem spanning across multiple process executions, not strictly tied to just git so we need to apply a fix globally.

**Comment by cmoulliard** [comment]
> Thank you for reporting this. This will likely be a problem spanning across multiple process executions, not strictly tied to just git so we need to apply a fix globally.

The stack trace should be at least logged or trapped to report by example the following error as it helps the user to understand
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v --force --tags -- origin
  stderr: 'fatal: remote error: upload-pack: not our ref f06ea2185060f86690509c03faa793875bf0e221'
Current commit: 262cc4839eae9a07cd8ed0839ab33a15aad5f056
```

**Comment by eskultety** [comment]
I'll just make a note that we most certainly don't want to log tracebacks as those can not only contain useful data, but also sensitive data which you don't want in production pipelines, so this is solely matter of a descriptive error message.

**Comment by eskultety** [comment]
**Closing as this was fixed upstream a while ago.** A sample debug log output with latest hermeto:
```
2025-11-19 16:06:16,358 ERROR FetchError: Failed to fetch the tags on the Git repository (GitCommandError) for /var/tmp/fail-fetch-test2/tmpnppcmg_u.hermeto-source-copy: Cmd('git') failed due to: exit code(1)\n  cmdline: git fetch -v --force --tags -- origin\n  stderr: 'fatal: remote error: upload-pack: not our ref 29816b5b187e0348feb6ebc9ba8f3768d7f29554'
Error: FetchError: Failed to fetch the tags on the Git repository (GitCommandError) for /var/tmp/fail-fetch-test2/tmpnppcmg_u.hermeto-source-copy: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v --force --tags -- origin
  stderr: 'fatal: remote error: upload-pack: not our ref 29816b5b187e0348feb6ebc9ba8f3768d7f29554'
  The error might be intermittent, please try again.
  If the issue seems to be on the hermeto side, please contact the maintainers.
```

That said we may want to revisit our internals to refine some rough edges on how this all is reported and in what contexts (e.g. is the error log code path the same for git errors vs other external commands)? However, that is a refactor for another day and currently lacking any priority for the team.
